name: Build Atari800 for WIN

on:
  workflow_dispatch:

jobs:
  build-windows-msys2:
    name: MSYS2 Build on Windows
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            base-devel
            mingw-w64-x86_64-toolchain
            autoconf
            automake
            libtool

      - name: Run autoreconf
        run: autoreconf -fiv

      - name: Configure project
        run: ./configure

      - name: Build project
        run: make -j$(nproc)

      - name: Verify build
        run: |
          if [ ! -f src/atari800.exe ]; then
            echo "Build failed"
            exit 1
          fi
          echo "Build succeeded"
